/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencvandroidboilerplate_MainActivity */

#ifndef _Included_com_example_opencvandroidboilerplate_MainActivity
#define _Included_com_example_opencvandroidboilerplate_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencvandroidboilerplate_MainActivity
 * Method:    processFrame
 * Signature: (JJ[I)I
 */
JNIEXPORT jint JNICALL Java_com_example_opencvandroidboilerplate_MainActivity_processFrame
  (JNIEnv *, jobject, jlong, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
