/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_coolcall_CallActivity */

#ifndef _Included_com_example_coolcall_CallActivity
#define _Included_com_example_coolcall_CallActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_coolcall_CallActivity
 * Method:    processFrame
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_coolcall_CallActivity_processFrame
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
